# tetris-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test6
spec:
  replicas: 2 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: test6
  template:
    metadata:
      labels:
        app: test6
    spec:
      containers:
        - name: test6
          image: nasi101/tetris # Replace with the actual image tag
          ports:
            - containerPort: 80 # Replace with the port your Tetris game listens on
